---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    # update-types:
    #   - "version-update:semver-major"
    #   - "version-update:semver-minor"
    #   - "version-update:semver-patch"
