---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/java"
    groups:
      vulnerable-dependecies:
        applies-to: version-updates
        pattern:
          - "*"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "com.jayway.jsonpath:json-path"
        versions: [ ">= 2.8.0" ]
      - dependency-name: "commons-beanutils:commons-beanutils"
        versions: [ "1.11.0"]
